### ISSUE TITLE
Dagger Annotation Processor Crashes When Building With Groovy

### ISSUE THREAD

**Issue by Sarev0k** [groovy/groovy-android-gradle-plugin#32]
I've created the a sample Gradle project to demonstrate the problem
1. [Download the zip](https://gist.github.com/Sarev0k/045c1d56fdd271e9784d/raw/18c0e1758844a3aed204d224b8f1ffc370dc16ca/GroovyDaggerGuavaFailureDemo.zip)
2. Extract
3. Modify the local.properties to point at your Android SDK
4. ./gradlew build --stacktrace

```
    :preBuild
    :compileDebugNdk
    :preDebugBuild
    :checkDebugManifest
    :prepareDebugDependencies
    :compileDebugAidl
    :compileDebugRenderscript
    :generateDebugBuildConfig
    :generateDebugAssets UP-TO-DATE
    :mergeDebugAssets
    :generateDebugResValues UP-TO-DATE
    :generateDebugResources
    :mergeDebugResources
    :processDebugManifest
    :processDebugResources
    :generateDebugSources
    :compileDebugJava
    :compileDebugGroovy
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    :compileDebugGroovy FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileDebugGroovy'.
    > java.lang.NoSuchMethodError: com.google.common.collect.Queues.newArrayDeque()Ljava/util/ArrayDeque;

    * Try:
    Run with --info or --debug option to get more log output.

    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileDebugGroovy'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
    Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.google.common.collect.Queues.newArrayDeque()Ljava/util/ArrayDeque;
    at com.sun.tools.javac.main.Main.compile(Main.java:469)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
    at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler$2$1.compile(ApiGroovyCompiler.java:112)
    at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:122)
    at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:47)
    at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Queues.newArrayDeque()Ljava/util/ArrayDeque;
    at dagger.internal.codegen.InjectBindingRegistry.<init>(InjectBindingRegistry.java:68)
    at dagger.internal.codegen.ComponentProcessor.init(ComponentProcessor.java:99)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:517)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:614)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:707)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    ... 11 more
```

I've uploaded [logs at the --debug log level](https://gist.github.com/Sarev0k/045c1d56fdd271e9784d/raw/eb305209def0a4295b2e9e7d048249a8e662e3d5/GroovyDaggerGuavaFailure.log) for your references.

Oddly enough, if you were to move the AndroidModule.java file form src/main/groovy to src/main/java this project compiles with no issues.  I've uploaded [logs at the --debug log level](https://gist.github.com/Sarev0k/045c1d56fdd271e9784d/raw/78016f875d45d3a0aaad45a0a3088abbc9174aa3/JavaDaggerGuavaSuccess.log) for this case as well.

Do you have any ideas for what might be causing this issue?

Thanks for your help.

**Comment by melix** [comment]
Thanks for the update!

**Comment by mg6maciej** [comment]
Hey @Sarev0k,
Is there a workaround for this issue when using Cedric's plugin until this is fixed in Gradle ( https://github.com/gradle/gradle/pull/384 )?  
Seems I've been following your footsteps, but I don't know how would I disable forking for groovyCompile on Android.

**Comment by Sarev0k** [comment]
You need to do the following:

    androidGroovy {
        options {
            groovyOptions.with {
                fork = false
            }
        }
    }

However, once you get past this, you're going to run into [this issue](https://groups.google.com/forum/#!msg/gradle-dev/CvkFHRve3Sk/EkOU4liL7X8J).

I've got a [pull request](https://github.com/gradle/gradle/pull/384) open to fix this issue, but it hasn't been merged yet.  I've been told that Gradle 2.4 will be the earliest version of Gradle that this makes it into.

**Comment by mg6maciej** [comment]
Thanks for a really quick reply. I tried this snippet (could have figured it out from this repo's README.md) and that part worked. As you predicted, I also run into an issue, where stubs are not checked for annotations.

I switched to original Dagger as a last resort before abandoning Groovy... and it works. Didn't even have to disable forking.

**Comment by Sarev0k** [comment]
Are you sure you're using the original dagger in static mode instead of dynamic mode?

In Gradle builds, I'd expect the annotation processor not to process annotations on groovy stubs regardless of what version of dagger you're using.

The only way you could get around that I believe is if dagger is using reflection to do dependency injection.  And if that's the case, in not sure how much more performant it is to guice on Android.

**Comment by mg6maciej** [comment]
You are correct about such setup using dynamic mode. I see no `$$InjectAdapter` classes in `build/` directory and there is normally plenty of them.  
I'll stick to it for now and compile your fork of Gradle if there will be need for a faster startup.

**Comment by cgruber** [comment]
Ok - I'm sorry I missed this ping - and am only getting up to speed on it now.  The specific issue in play was a guava version mismatch, as com.google.common.collect.Queues.newArrayDeque.  But I'd have to dig in and replicate this a bit.   It is entirely possible that it works with latter daggers because there's an implicit dep on Guava at a later version, so you're getting the later version which then has this method.

I'm not sure if the issue is gradle related or a mis-configuration. If the build tool/compiler classpath is not aligned with the dagger-compiler plugin, it's entirely possible that this issue could rear its head the way it seems to above.  

The issue could be fixed by shading (jar-jaring, whatever) dagger as we have with AutoValue and the like.  In such a case it would have no deps conflicts (reasonable since it's a deployable binary in a sense anyway) but that would simply mean that dagger is resistant to isolation issues in your setup, but those isolation issues remain.

**Comment by Sarev0k** [comment]
Hi @cgruber this was a bug with how Gradle isolates its classpath for forked builds.

There's already an [issue file to fix this](http://forums.gradle.org/gradle/topics/gradle-overrides-the-specified-guava-dependencies-with-its-own-when-running-an-annotation-processor-from-a-groovy-build)

I don't think jar-jaring should be necessary.

**Comment by cgruber** [comment]
Ok - though for other reasons I plan to do it (avoiding incompatible guava
versions or auto-common versions between processors, etc.)

**Comment by cgruber** [comment]
(thanks though!)

**Comment by Sarev0k** [comment]
Gradle 2.4 is shipping with [a fix to this issue](https://github.com/gradle/gradle/commit/b314657372f567dd3755f8a1758df813f2bc8599).

It's also introducing a change that allows [java annotation processors to run against Groovy stubs](https://github.com/gradle/gradle/blob/6a81c2e8cfecb5e5ea7498ed8a9eda23f4d6d852/subprojects/docs/src/docs/release/notes.md#support-for-annotation-processing-of-groovy-code).

**Comment by mg6maciej** [comment]
That's a great news. Thanks Will!
That's one reason not to use Groovy for Android going to disappear.

**Comment by FireZenk** [comment]
Im trying to get it work (Dagger2 + Groovy) and it does not auto-generate classes (DaggerGlobalComponent):

Application:
````
component = DaggerGlobalComponent.builder()
                .busModule(new BusModule())
                .serviceModule(new ServiceModule())
                .contextModule(new ContextModule(this))
                .persistenceModule(new PersistenceModule(this))
                .build();
````

build.gradle:
````
androidGroovy {
    options {
        sourceCompatibility = '1.7'
        targetCompatibility = '1.7'
        groovyOptions.fork = false
    }
}
````

gradle-wrapper.properties:
````
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip
````

any ideas?

**Comment by Sarev0k** [comment]
It works for me.

I've created [the following demo](https://gist.github.com/Sarev0k/045c1d56fdd271e9784d/raw/335e2e600890c025645b009b3e668d8b92735a34/GroovyDagger2Demo.zip) that demonstrates it working.

Your problem is most likely caused by your DaggerGlobalComponent being named differently than you think.  If it's an inner class of an Application for instance, it would be called DaggerMyApplicationName_GlobalComponent.

If you take a look at your generated java sources under `build/intermediates/classes/debug/your/package/name/`, you should be able to figure out what your component is called.

**Comment by FireZenk** [comment]
@Sarev0k with your demo:

````
Error:Execution failed for task ':compileDebugAidl'.
> Executor Singleton not started
````

And on generated sources folder of my project:

````
BuildConfig.class
Manifest.class
Manifest$permission.class
R.class
R$anim.class
R$attr.class
R$bool.class
R$color.class
R$dimen.class
R$drawable.class
R$id.class
R$integer.class
R$layout.class
R$mipmap.class
R$plurals.class
R$raw.class
R$string.class
R$style.class
R$styleable.class
````

**Comment by Sarev0k** [comment]
That demo works.  Make sure you've modified the project.properties to point at your android SDK.

Since you don't have any generated classes it doesn't look like you've defined your dependencies on Dagger2 correctly in your build.gradle.

If you would like more help, please recreate your issue with a simple project and provide a link to a zip of it.

**Comment by FireZenk** [comment]
Here is the project, launching them you can reproduce the issue: https://github.com/FireZenk/maat
Also into ```MaatApplication.groovy``` you can see that ```DaggerGlobalComponent``` can't be imported
Thanks for your help

**Comment by Sarev0k** [comment]
Build is failing because of this error:
```
/home/werickson/temp/maat/app/build/tmp/compileDevelDebugGroovy/groovy-java-stubs/org/firezenk/maat/managers/BaseActivity.java:10: error: cannot access DrawerLayoutImpl
public abstract class BaseActivity
                ^
  class file for android.support.v4.widget.DrawerLayoutImpl not found
startup failed:
Compilation failed; see the compiler error output for details.
```

I don't think this is a very simple sample.  Looking at the build.gradle for this package, there are a lot of moving parts, including additional plugins that are likely to introduce noise into this investigation.

Can you please reproduce this in a package that just integrates with Gradle, Groovy, Dagger2 and Android using no other plugins or dependencies?  This will allow us to better isolate what your problem really is.

I've verified that the sample project I already linked you to works on multiple machines.  Perhaps you should try to figure out why that sample is failing on your machine, as there might be something wrong with your setup.

**Comment by mg6maciej** [comment]
The `DrawerLayoutImpl` issue is "normal" for me. You just need to build the app again and it will work. Issue was also described here: https://github.com/groovy/groovy-android-gradle-plugin/issues/34

**Comment by Sarev0k** [comment]
You're right, building again solved that issue.  However, this project's build still fails due to a Crashalytics problem:
```
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: CRASHLYTICS_API_KEY. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@crashlytics.com for assistance.
```

However, I did get far enough to see that Dagger2 did generate the class that @FireZenk said was missing:
```
$ tree ./app/build/intermediates/classes/production/debug/org/firezenk/maat/
./app/build/intermediates/classes/production/debug/org/firezenk/maat/
├── annotations
│   └── AnnotationParser.class
├── BuildConfig.class
├── fragments
│   └── BaseFragment.class
├── MaatApplication.class
├── managers
│   ├── BaseActivity.class
│   └── MainActivity.class
├── Manifest.class
├── Manifest$permission.class
├── modules
│   ├── BusModule.class
│   ├── BusModule_ProvideEventBusFactory.class
│   ├── BusModule_ProvideEventBusFactory.java
│   ├── ContextModule.class
│   ├── ContextModule_ProvideContextFactory.class
│   ├── ContextModule_ProvideContextFactory.java
│   ├── DaggerGlobalComponent$1.class
│   ├── DaggerGlobalComponent$Builder.class
│   ├── DaggerGlobalComponent.class
│   ├── DaggerGlobalComponent.java
│   ├── GlobalComponent.class
│   ├── PersistenceModule.class
│   ├── PersistenceModule_ProvidePersistenceFactory.class
│   ├── PersistenceModule_ProvidePersistenceFactory.java
│   ├── ServiceModule$1.class
│   ├── ServiceModule.class
│   ├── ServiceModule_ProvideServiceFactory.class
│   └── ServiceModule_ProvideServiceFactory.java
├── network
│   ├── MaatService.class
│   └── TokenEntity.class
├── persistence
│   └── Persistence.class
├── R$anim.class
├── R$attr.class
├── R$bool.class
├── R.class
├── R$color.class
├── R$dimen.class
├── R$drawable.class
├── R$id.class
├── R$integer.class
├── R$layout.class
├── R$mipmap.class
├── R$string.class
├── R$styleable.class
├── R$style.class
├── utils
│   ├── DateUtils.class
│   └── Preferences.class
└── views
    └── notifications
        └── PushNotificationsReceiver.class
```

And it looks like the reason why `DaggerGlobalComponent` is unable to be imported is because you're missing the import for this class.

From the above output you can see that DaggerGlobalComponent's full path is:
`org.firezenk.maat.modules.DaggerGlobalComponent`

However, the class that's referencing it has the path of:
`org.firezenk.maat.MaatApplication`

If classes aren't in the same Java package, an import is required.

**Comment by FireZenk** [comment]
Regarding crashlytics issue: you need an api_key or remove the following line on the Android Manifest:
```<meta-data android:name="com.crashlytics.ApiKey" android:value="CRASHLYTICS_API_KEY"/> ```

Also comment lines from 30 to 35 of MaatAplication is needed.

I tried to put: ``` import org.firezenk.maat.modules.DaggerGlobalComponent ``` on MaatApplication.groovy and IDE say that cannot resolve it

**Comment by Sarev0k** [comment]
> I tried to put: import org.firezenk.maat.modules.DaggerGlobalComponent on MaatApplication.groovy and IDE say that cannot resolve it

This is expected.  Android Studio is kind of crap when it comes to its annotation processor integration.

However, building from Android Studio or command line should still work, and you shouldn't have a runtime failure when trying to use that class.

Perhaps the Dagger2 folks have some suggestions for the best way to resolve generated sources in Android Studio.

**Comment by mg6maciej** [comment]
Most people use `apt` instead of `provided` for compile-time dependencies like dagger-compiler.

Here is some info how to set it up: https://bitbucket.org/hvisser/android-apt
