### ISSUE TITLE
Map coercion not working in an Android test.

### ISSUE THREAD

**Issue by bmax-moblin** [groovy/groovy-android-gradle-plugin#72]
I am trying to mock a POJO class in my androidTest using Map coercion but I get the following exception:

java.lang.UnsupportedOperationException: can't load this type of class file
at java.lang.VMClassLoader.defineClass(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:292)
at java.lang.ClassLoader.defineClass(ClassLoader.java:256)
at org.codehaus.groovy.runtime.ProxyGeneratorAdapter$InnerLoader.defineClass(ProxyGeneratorAdapter.java:924)
at org.codehaus.groovy.runtime.ProxyGeneratorAdapter.<init>(ProxyGeneratorAdapter.java:189)
at groovy.util.ProxyGenerator.instantiateAggregate(ProxyGenerator.java:167)
at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:120)
at groovy.util.ProxyGenerator.instantiateAggregateFromBaseClass(ProxyGenerator.java:106)
at org.codehaus.groovy.runtime.DefaultGroovyMethods.asType(DefaultGroovyMethods.java:10727)
at org.codehaus.groovy.runtime.dgm$53.doMethodInvoke(Unknown Source)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:902)
at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:893)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:166)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:589)

**Comment by melix** [comment]
Hi! This is a limitation of Groovy on Android itself. Map coercion sometimes requires generation of classes at runtime, and unfortunately this is not possible on Android. As a workaround, you can use an anonymous inner class.

**Comment by bmax-moblin** [comment]
Got it, thanks!
