### ISSUE TITLE
compileReleaseUnitTestGroovy is failing on Jenkins

### ISSUE THREAD

**Issue by tehras** [groovy/groovy-android-gradle-plugin#76]
./gradlew build is working perfectly fine locally, however when i try it on our Jenkins server (Red Hat Enterporise Linux Server release 6.7), it is failing. Below is the exception. Has anyone else seen similar issues? 

```
16:18:27 * Exception is:
16:18:27 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileReleaseUnitTestGroovy'.
16:18:27 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
16:18:27 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
16:18:27 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
16:18:27 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
16:18:27 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
16:18:27 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
16:18:27 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
16:18:27 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
16:18:27 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
16:18:27 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
16:18:27 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
16:18:27 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
16:18:27 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
16:18:27 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
16:18:27 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
16:18:27 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
16:18:27 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
16:18:27 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
16:18:27 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
16:18:27 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
16:18:27 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
16:18:27 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
16:18:27 	at org.gradle.internal.Factories$1.create(Factories.java:22)
16:18:27 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
16:18:27 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
16:18:27 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
16:18:27 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
16:18:27 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
16:18:27 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
16:18:27 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
16:18:27 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
16:18:27 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
16:18:27 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
16:18:27 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
16:18:27 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
16:18:27 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
16:18:27 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
16:18:27 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
16:18:27 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
16:18:27 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
16:18:27 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
16:18:27 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
16:18:27 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
16:18:27 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
16:18:27 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
16:18:27 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
16:18:27 	at org.gradle.launcher.Main.doAction(Main.java:33)
16:18:27 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
16:18:27 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
16:18:27 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
16:18:27 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
16:18:27 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
16:18:27 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
16:18:27 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
16:18:27 Caused by: java.lang.NoClassDefFoundError: android/support/v4/app/ActivityCompatApi23$RequestPermissionsRequestCodeValidator
16:18:27 	at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:50)
16:18:27 	at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:50)
16:18:27 	at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:50)
16:18:27 	at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:50)
16:18:27 	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:151)
16:18:27 	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:51)
16:18:27 	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
16:18:27 	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
16:18:27 	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
16:18:27 	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
16:18:27 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
16:18:27 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
16:18:27 Caused by: java.lang.ClassNotFoundException: android.support.v4.app.ActivityCompatApi23$RequestPermissionsRequestCodeValidator
16:18:27 	at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:41)
16:18:27 	... 12 more
```

**Comment by pieces029** [comment]
Do you have the support libraries installed on your ci machine?

**Comment by tehras** [comment]
Yeah we have the supp library there.

I think this is happening because library - internal_impl-23.0.1.jar is compiled inside the libs of support-v4 and not classes.jar like all the other libraries are. I assume that this plugin only looks for classes.jar for the jars.

**Comment by pieces029** [comment]
It has access to all libraries the javaCompile task has, so that doesn't sound like the issue.

**Comment by pieces029** [comment]
Android source code isn't available in unit tests so this would fail to compile in both using java or groovy if you are referencing ActivityCompat anywhere in the tests. In order to do testing with Android components you want the test to be located in androidTest folder.

**Comment by tehras** [comment]
It actually compiles all the Java tasks and even the javaUniTest tasks. Anyways, for now I moved the internal-impl.jar where this class was to my build.gradle and that worked. Also I just saw you posted 0.3.7 so I'll upgrade to that and see if the issue still happens

**Comment by pieces029** [comment]
anything to report back using 0.3.7 or 0.3.8-SNAPSHOT?

**Comment by pieces029** [comment]
Anything to report back using 0.3.8 or 0.3.9-SNAPSHOT?

**Comment by tehras** [comment]
Hey sorry, been a bit busy. I tried 0.3.9 but that didn't work for other reasons. I think you can close this for now, I'll try again soon, and see if I see any differences
